server:
  port: 8181

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
google:
  oauth2:
    client-id: 746309681103-5jb4g12c5kn08olp6j5ck7v5bm9630ve.apps.googleusercontent.com
---
server:
  port: 80
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
google:
  oauth2:
    client-id: 746309681103-5jb4g12c5kn08olp6j5ck7v5bm9630ve.apps.googleusercontent.com