server:
  port: 8181
ui:
  inspect-url: http://localhost:3001/inspect/
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    username: noreplyrequestmanager@gmail.com
    password: requestmanager
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
google:
  oauth2:
    client-id: 746309681103-5jb4g12c5kn08olp6j5ck7v5bm9630ve.apps.googleusercontent.com
logging:
  level:
    org.springframework: DEBUG
---
server:
  port: 80
ui:
  inspect-url: https://sapientia-request-manager-ui.herokuapp.com/inspect/
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  mail:
    host: smtp.gmail.com
    username: noreplyrequestmanager@gmail.com
    password: requestmanager
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000

google:
  oauth2:
    client-id: 746309681103-5jb4g12c5kn08olp6j5ck7v5bm9630ve.apps.googleusercontent.com


