server:
  port: 8181
google:
  oauth2:
    client-id: 746309681103-5jb4g12c5kn08olp6j5ck7v5bm9630ve.apps.googleusercontent.com
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sapientia_requests?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
